language: go
go:
- 1.8
install:
- make setup-ci
script:
- make test
env:
  global:
  - secure: EVSBMvyukNBDQ+dXwIoYhzqYb0hNJ8S7+JGVLf6YDY468ZbNyQ1CbK62trQ2mIYiWAyq2JA2ouy1xVGfnVqK7h3+ZPIs94Unv2U7uoGdUCnuXHMPLZHBMbSUeDrlwakkKyZYJJH5MYi2FmH/fdJGdMzssNsXC0lwz4TdImkxLSTgHlgS82AveGjZ/eKDPv/5I7ALnuSYMlKFQsaO7NQf69Wha9pcr0P9RGcoeKtJ2buQLTLMABaiBRXZ0Ixa5qYQR4lXOWtRg1wra69MYsxxOZxU2/6HSNbWuR8q0bWTZj4muxDw0tASthwkxna6DWUG4hgB26fXpfnOvjpgJc1kZ3Zt7qWHXvMZKYu5InNEVtf2iv8JPe6cjxHwBOLfwJ/vLxk29MmESkyu4yZ3mZU+1CsFuUZY80L9QpnpK3W+A7rxFKdGQ4cblInABsHpR4qZ/pDWKLRU2+UL4eci7fmwZ2rbHhmCnEmVCFtBtorG9TXj0xwEVW65chee05CRhDeg3te972JZfhPj8dB35M6XJOLi3kvpMTctxOuAfCKkwZ16n2JKPfBgicjkQ5a93Gh6y6h+lRVl/gY+nVHSSrf53irP2Hpc2HjWNk675naJ7xQms1zx6gHDf/q+Cg++mOLC4RTLp/sUKgpLb9a8H+aojk+pQF0Iazqu3SLsLQwZ47c=
  - secure: YNjI/M24GkNWH1GuSeoc8vHNPAZZWRKr4+RSbHYafGANZDmAX/uyVDtXZMzFM+wWWBh9i2Brj3RePczlojj5myehyBkqT7t++bk2Z9xEWH2wYPBJ2y+Iv0nUUFAfgFkAPO5lYVfJ4n1ujN/D/uH61MlxAWejDf+TfOrE+mO/jaZenCcCJ9VyRlHz4f5x2PTIs1+C0wPvBDW8e0RMmE1trWV4AcoKQFEE/2++UJ9YsGKNIIP221YhncAaair1hQF02sgRaQxMUH141l+JKjGNXCGauk1eC7vjWhYQEnJNyXaAKjUVK8nrHy/8R1WhgteqMUX8gcvHScclTfDrhxPwUrKoWlzbw/z+hL7DBe67qIviZhli7ol8sVVWdCVXzOUoS6VjrnZo+MQogelAXcb6eKZd8pKCuZybdf73NVijp5TmgsEJg/+mnEd1PFmK5bfDKW27Okk4ne7TovBFjexAMUGvtETOyar/aASy7h1dUKWpTS9qCLVWWRxiIM/Zu+ewb9jO4EyZSpKW2BNwOjsxo1cUusFGTjLmq2U8w4w06unoaJTgzu8l12FW+YicldHfOMUm9RQVB6UGlLwLYReOYDnPgM223dEqak+eF51SUZwyseqkm3wYSsDxTqFMS6utnYWIV11/FdbQAFRvYD6P2IFNP4mdVDQ0uuEb5v9VEDo=
after_success: bash after-success.sh
