---
apiVersion: v1
kind: Service
metadata:
  name: mystack-router
spec:
  selector:
    app: mystack-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 28000
      name: tcp
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mystack-router
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mystack-router
    spec:
      containers:
        - name: mystack-router
          image: tfgco/mystack-router:v1
          ports:
            - containerPort: 8080
            - containerPort: 28000
