---
apiVersion: v1
kind: Service
metadata:
  name: mystack-router
spec:
  selector:
    app: mystack-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mystack-router
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: mystack-router
    spec:
      containers:
        - name: mystack-router
          image: quay.io/tfgco/mystack-router:v{{ .Chart.Version }}
          ports:
            - containerPort: 8080
          env:
          - name: MYSTACK_KUBERNETES_SERVICE_DOMAIN_SUFFIX
            value: {{ .Values.domain }}
